// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6lUTr6mDeNE8TrO5YTOoCyhMvzhkJOU',
    appId: '1:119728263909:web:b59c2e05d9229622bf7a0c',
    messagingSenderId: '119728263909',
    projectId: 'flutter-task-c1674',
    authDomain: 'flutter-task-c1674.firebaseapp.com',
    storageBucket: 'flutter-task-c1674.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenYolulTd3nRqva6mDL7SRQbh4Pu2dIg',
    appId: '1:119728263909:android:bad509f337ac4a5dbf7a0c',
    messagingSenderId: '119728263909',
    projectId: 'flutter-task-c1674',
    storageBucket: 'flutter-task-c1674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNzIMUUsTHb3lQZdxrKLvIUnYGSAOwIOg',
    appId: '1:119728263909:ios:b4bfb53085307db8bf7a0c',
    messagingSenderId: '119728263909',
    projectId: 'flutter-task-c1674',
    storageBucket: 'flutter-task-c1674.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNzIMUUsTHb3lQZdxrKLvIUnYGSAOwIOg',
    appId: '1:119728263909:ios:b4bfb53085307db8bf7a0c',
    messagingSenderId: '119728263909',
    projectId: 'flutter-task-c1674',
    storageBucket: 'flutter-task-c1674.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk6lUTr6mDeNE8TrO5YTOoCyhMvzhkJOU',
    appId: '1:119728263909:web:8c197e53f583e535bf7a0c',
    messagingSenderId: '119728263909',
    projectId: 'flutter-task-c1674',
    authDomain: 'flutter-task-c1674.firebaseapp.com',
    storageBucket: 'flutter-task-c1674.firebasestorage.app',
  );

}